version: 1
id: history_inventory
kind: agent_pipeline
description: Produce a structured inventory of a Galaxy history

start: api_histories

inputs:
  transcripts:
    type: transcript_stream
  context:
    type: object

state:
  histories:
    type: array
  history:
    type: object
  contents:
    type: array
  dataset_count:
    type: integer
  has_errors:
    type: boolean
  summary:
    type: string

nodes:

  api_histories:
    type: executor
    run:
      op: api.call
      target: galaxy.histories.get
      input:
        limit: 10
    emit:
      state.histories: result
    next: pick_history

  pick_history:
    type: planner
    prompt: |
      Select a history to inspect.
    enum_from:
      state: histories
      field: name
    output_schema:
      type: object
      required: [next, history_name]
      properties:
        next:
          type: string
          enum: [api_contents]
        history_name:
          type: string
    emit:
      state.history:
        name:
          $ref: result.history_name
        next:
          $ref: result.next
    next:
      $ref: state.history.next

  api_contents:
    type: executor
    run:
      op: api.call
      target: galaxy.histories.show.contents.get
      input:
        history_id:
          $expr:
            op: lookup
            from:
              $ref: state.histories
            match:
              field: name
              equals:
                $ref: state.history.name
            select: id
    emit:
      state.history:
        id:
          $ref: run.input.history_id
      state.contents: result
    next: compute_dataset_count

  compute_dataset_count:
    type: compute
    emit:
      state.dataset_count:
        $expr:
          op: len
          arg:
            $ref: state.contents
    next: compute_error_flag

  compute_error_flag:
    type: compute
    emit:
      state.has_errors:
        $expr:
          op: any
          from:
            $ref: state.contents
          field: state
          equals: error
    next: summarize_contents

  summarize_contents:
    type: reasoning
    prompt: |
      Write a concise human-readable summary of a Galaxy history.

      Facts you can rely on:
      - dataset_count: {{dataset_count}}
      - has_errors: {{has_errors}}

      Explain the overall contents in natural language.
      Do not restate numbers mechanically.
    input:
      history:
        $ref: state.history
      contents:
        $ref: state.contents
      dataset_count:
        $ref: state.dataset_count
      has_errors:
        $ref: state.has_errors
    emit:
      state.summary:
        $ref: result
    next: done

  done:
    type: terminal
    output:
      history:
        id:
          $ref: state.history.id
        name:
          $ref: state.history.name
      dataset_count:
        $ref: state.dataset_count
      has_errors:
        $ref: state.has_errors
      summary:
        $ref: state.summary
