# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: aysam.guerler@gmail.com
author_name: Aysam Guerler
has_binder: true
has_settings: false
kind: frontend
labextension_name: jl_galaxy
project_short_description: Connect to Galaxy
python_name: jl_galaxy
repository: https://github.com/guerler/jl-galaxy
test: false

